#!/bin/bash

function all {
    run
}

function run {
    if scons; then
        godot --path godot -f $*
    fi
}

function bench {
	if scons bench; then
		./bench
	fi
}

function build {
    declare -A ext=( [linux]="" [macos]=".app" [windows]=".exe" )
	if scons target=template_release platform=$1; then
	    godot --path godot --export-release $1 ../bin/electro${ext[$1]}
	fi
}

function edit {
    ( godot godot/project.godot >/dev/null 2>&1 & )
}

function fmt {
    scons compile_commands.json
    clang-format -i cpp/*.cpp cpp/*.h
}

function present {
	echo next: stokes complexity graph
	read
	open media/time_graph.png
    echo next: electro demonstration
    read
	bin/electro -f
}
