#!/bin/bash

function all {
    run
}

function run {
    if scons; then
        godot --path godot -f $*
    fi
}

function build {
    declare -A ext=( [linux]="" [macos]=".dmg" [windows]=".exe" )
	scons target=template_release platform=$1
	godot --path godot --export-release $1 ../bin/electro${ext[$1]}
}

function edit {
    ( godot godot/project.godot >/dev/null 2>&1 & )
}

function fmt {
    clang-format -i cpp/*.cpp cpp/*.h
}
